"""initial schema

Revision ID: 33024e459000
Revises: 
Create Date: 2026-06-05 12:42:28.339012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33024e459000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_base_url'), ['base_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_started_at'), ['started_at'], unique=False)

    op.create_table('uptime_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uptime_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uptime_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uptime_checks_target_url'), ['target_url'], unique=False)
        batch_op.create_index('ix_uptime_target_time', ['target_url', 'checked_at'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('page_url', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_url', 'fingerprint', name='uq_incident_target_fp')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_target_status', ['target_url', 'resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_target_url'), ['target_url'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('page_url', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('dispatch_status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_fired', ['fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index('ix_alerts_incident', ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'run_id', name='uq_obs_incident_run')
    )
    with op.batch_alter_table('incident_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_observations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_observations_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_observations_run_id'))
        batch_op.drop_index(batch_op.f('ix_incident_observations_incident_id'))

    op.drop_table('incident_observations')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index('ix_alerts_incident')
        batch_op.drop_index(batch_op.f('ix_alerts_fired_at'))
        batch_op.drop_index('ix_alerts_fired')

    op.drop_table('alerts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_target_url'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_incidents_category'))
        batch_op.drop_index('ix_incident_target_status')

    op.drop_table('incidents')
    with op.batch_alter_table('uptime_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_uptime_target_time')
        batch_op.drop_index(batch_op.f('ix_uptime_checks_target_url'))
        batch_op.drop_index(batch_op.f('ix_uptime_checks_checked_at'))

    op.drop_table('uptime_checks')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_runs_base_url'))

    op.drop_table('runs')
    # ### end Alembic commands ###
